# Generated by Django 4.2.6 on 2023-10-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembatch',
            name='batch',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemCode',
            field=models.CharField(max_length=200),
        ),
    ]
