# Generated by Django 4.2.6 on 2023-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_itembatch_batch_alter_item_itemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembatch',
            name='batch',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
