# Generated by Django 4.2.6 on 2023-11-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_itembatch_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
