# Generated by Django 4.2.6 on 2023-10-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=125, null=True),
        ),
    ]
