# Generated by Django 4.2.6 on 2023-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_customer_customer_ob_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_ob_date',
            field=models.DateField(null=True),
        ),
    ]
