# Generated by Django 4.2.6 on 2023-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_customer_customer_ob_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_slno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_slno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_phone1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_phone2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_slno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_trn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
