# Generated by Django 4.2.6 on 2023-10-09 10:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=70)),
                ('thumb', models.ImageField(blank=True, default='default.png', null=True, upload_to='staffimage')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('arabic_name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=125, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('other', 'OTHER')], max_length=10)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('language', models.CharField(choices=[('English', 'ENGLISH'), ('Arabic', 'ARABIC'), ('Hindi', 'HINDI'), ('French', 'FRENCH'), ('Other', 'OTHER')], default='English', max_length=10)),
                ('permannent_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('permannent_address2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('emergency', models.CharField(blank=True, max_length=15, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('joined_as_trainee', models.DateField(blank=True, null=True)),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('staff_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Resigned', 'Resign'), ('Terminated', 'Terminate')], default='Active', max_length=20)),
                ('is_staff_left', models.BooleanField(default=False)),
                ('passport_number', models.CharField(blank=True, max_length=128, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('is_passport_expiry_notif_send', models.BooleanField(default=False)),
                ('visa_type', models.CharField(choices=[('Visit Visa', 'VISIT VISA'), ('Work Visa', 'WORK VISA'), ('Own Visa', 'OWN VISA'), ('Other Visa', 'OTHER VISA')], default='work visa', max_length=20)),
                ('visa_number', models.CharField(blank=True, max_length=128, null=True)),
                ('visa_issue_date', models.DateField(blank=True, null=True)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('is_visa_expiry_notif_send', models.BooleanField(default=False)),
                ('driv_licence_number', models.CharField(blank=True, max_length=128, null=True)),
                ('driv_licence_issue_date', models.DateField(blank=True, null=True)),
                ('driv_licence_expiry_date', models.DateField(blank=True, null=True)),
                ('is_driv_licence_expiry_notif_send', models.BooleanField(default=False)),
                ('medical_insurance_number', models.CharField(blank=True, max_length=128, null=True)),
                ('medical_insurance_issue_date', models.DateField(blank=True, null=True)),
                ('medical_insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('is_medi_insurance_expiry_notif_send', models.BooleanField(default=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hra_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('communication_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('regular_holiday_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('public_holiday_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('halfday_fine', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fullday_fine', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('suspended', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
