# Generated by Django 4.2.6 on 2023-10-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='permannent_address1',
            new_name='permanent_address1',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permannent_address2',
            new_name='permanent_address2',
        ),
    ]
