# Generated by Django 4.2.6 on 2023-10-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupledger',
            old_name='if_trade_ac_flag',
            new_name='if_trade_ac',
        ),
    ]
