# Generated by Django 4.2.6 on 2023-10-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_rename_permannent_address1_employee_permanent_address1_and_more'),
        ('company', '0001_initial'),
        ('accounting', '0002_rename_if_trade_ac_flag_groupledger_if_trade_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='bank_sl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banksl', to='accounting.subledger'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='bankbook_sl_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bankbook', to='accounting.subledger'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='js_no1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='js1', to='accounting.daybook'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='js_no2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='js2', to='accounting.daybook'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='js_no3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='js3', to='accounting.daybook'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='js_no4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='js4', to='accounting.daybook'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='credit_sl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='accounting.subledger'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='debit_sl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit', to='accounting.subledger'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='groupledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='group_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.groupledger'),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
