# Generated by Django 4.2.6 on 2023-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_bankbook_bank_sl_alter_bankbook_bankbook_sl_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='bank_book_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='js_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='groupledger',
            name='gl_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='sl_no',
            field=models.IntegerField(),
        ),
    ]
