# Generated by Django 4.2.7 on 2023-11-10 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_company'),
        ('accounting', '0004_alter_bankbook_bank_book_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='js_no1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_transaction', to='accounting.daybook'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='js_no2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_charge', to='accounting.daybook'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='js_no3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bounced', to='accounting.daybook'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='js_no4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bounce_charge', to='accounting.daybook'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='reg_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='js_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='manual_voucher_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
