# Generated by Django 4.2.7 on 2023-11-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_subledger_ob_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
