# Generated by Django 4.2.7 on 2023-11-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_daybook_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subledger',
            name='ob_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
